"""
Django settings for door_calculator project.

Generated by 'django-admin startproject' using Django 4.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

M365_TENANT_ID = os.getenv("M365_TENANT_ID", "")
M365_CLIENT_ID = os.getenv("M365_CLIENT_ID", "")
M365_CLIENT_SECRET = os.getenv("M365_CLIENT_SECRET", "")

M365_AUTHORITY = f"https://login.microsoftonline.com/{M365_TENANT_ID}"
M365_SCOPE = ["https://graph.microsoft.com/.default"]

raw_sites = os.getenv("M365_SITE_DISPLAY_NAMES", "Проекти 2026,Переробка профілю 2026")
M365_SITE_DISPLAY_NAMES = [s.strip() for s in raw_sites.split(",") if s.strip()]
M365_DRIVE_NAME = os.getenv("M365_DRIVE_NAME", "Документи")
M365_ORDER_ROOT_FOLDER = os.getenv("M365_ORDER_ROOT_FOLDER", "Main")  # якщо замовлення НЕ в корені (типу "Main"), інакше пусто
M365_TECH_KEYWORD = os.getenv("M365_TECH_KEYWORD", "Чертежи в работу")
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-fojb6-3@+u%rw5r2#)i5*3ra%4i-wd%2ne^*--(@vfa@b&-v0s"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", True)

ALLOWED_HOSTS = ["4f62124b6562.ngrok-free.app", "localhost", "127.0.0.1", "173.242.54.102"]

CSRF_TRUSTED_ORIGINS = [
    "https://*.ngrok-free.app",
    "http://localhost",
    "http://127.0.0.1",
    "http://173.242.54.102"
]

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "doors",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "door_calculator.urls"
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'], 
        'APP_DIRS': True,  
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = "door_calculator.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'uk'

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [
    BASE_DIR / 'doors' / 'static',
]

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

M365_SYNC_CHAINS = {
    "precalc": [
        {"type": "child_contains", "value": "2-Комерційна пропозиція"},
        {"type": "child_all_contains", "value": "КП"},          # ✅ усі КП*
        {"type": "child_contains", "value": "1 Розрахунок матеріалів"},
        {"type": "search_all_contains", "value": "Для КС"},     # ✅ усі Для КС*
    ],
    "final": [
        {"type": "child_contains", "value": "4-Проектування"},
        {"type": "search_all_contains", "value": "Проект"},     # якщо їх може бути багато
        {"type": "child_contains", "value": "3 Креслення в роботу"},
        {"type": "search_all_contains", "value": "Для КС"},
    ],

    # --- переробки ---
    "rework_pre": [
        {"type": "child_contains", "value": "1 Креслення попередні"},
        {"type": "search_all_contains", "value": "Для КС"},
    ],
    "rework_final": [
        {"type": "child_contains", "value": "3 Креслення в роботу"},
        {"type": "search_all_contains", "value": "Для К.С"},
    ],
}