# Generated by Django 5.2.7 on 2025-10-29 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doors", "0002_remove_order_sketch_order_progress_order_status_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="progress",
            new_name="completion_percent",
        ),
        migrations.AddField(
            model_name="order",
            name="total_ks",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("in_progress", "В роботі"),
                    ("completed", "Завершено"),
                    ("postponed", "Відкладено"),
                ],
                default="in_progress",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
