# Generated by Django 5.2.7 on 2025-10-30 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doors", "0003_rename_progress_order_completion_percent_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Worker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("position", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
