# Generated by Django 5.2.7 on 2025-10-30 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doors", "0004_worker"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worklog",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="doors.worker"
            ),
        ),
        migrations.AlterField(
            model_name="worklog",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="doors.order",
            ),
        ),
    ]
