# Generated by Django 5.2.7 on 2025-10-30 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doors", "0005_alter_worklog_employee_alter_worklog_order"),
    ]

    operations = [
        migrations.RenameField(
            model_name="worklog",
            old_name="employee",
            new_name="worker",
        ),
        migrations.AlterField(
            model_name="worklog",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="doors.order"
            ),
        ),
    ]
