# Generated by Django 5.2.7 on 2025-10-30 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doors", "0006_rename_employee_worklog_worker_alter_worklog_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worklog",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="doors.order",
            ),
        ),
    ]
