# Generated by Django 5.2.7 on 2025-10-30 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doors", "0007_alter_worklog_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="sketch",
            field=models.ImageField(blank=True, null=True, upload_to="sketches/"),
        ),
    ]
