# Generated by Django 5.2.7 on 2025-10-30 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doors", "0008_order_sketch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
