# Generated by Django 5.2.7 on 2025-10-30 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doors", "0009_alter_order_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("percent", models.PositiveIntegerField(default=0)),
                ("comment", models.TextField(blank=True, null=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_logs",
                        to="doors.order",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
