# Generated by Django 5.2.7 on 2025-10-31 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doors", "0010_orderprogress"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "percent_done",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Відсоток виконання позиції на цю дату",
                        max_digits=5,
                    ),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                (
                    "order_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_history",
                        to="doors.orderitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Прогрес позиції",
                "verbose_name_plural": "Прогрес позицій",
                "ordering": ["-date"],
            },
        ),
    ]
