# Generated by Django 5.2.7 on 2025-11-12 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doors", "0011_itemprogress"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Назва категорії"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Опис"),
                ),
            ],
            options={
                "verbose_name": "Категорія",
                "verbose_name_plural": "Категорії",
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="addition",
            options={"verbose_name": "Доповнення", "verbose_name_plural": "Доповнення"},
        ),
        migrations.AlterModelOptions(
            name="coefficient",
            options={
                "verbose_name": "Коефіцієнт",
                "verbose_name_plural": "Коефіцієнти",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["category", "name"],
                "verbose_name": "Виріб",
                "verbose_name_plural": "Вироби",
            },
        ),
        migrations.AddField(
            model_name="addition",
            name="applies_globally",
            field=models.BooleanField(
                default=True, help_text="Якщо увімкнено — доступне для всіх виробів."
            ),
        ),
        migrations.AddField(
            model_name="addition",
            name="products",
            field=models.ManyToManyField(
                blank=True,
                help_text="Доступне для конкретних виробів.",
                related_name="additions",
                to="doors.product",
            ),
        ),
        migrations.AddField(
            model_name="coefficient",
            name="applies_globally",
            field=models.BooleanField(
                default=True,
                help_text="Якщо увімкнено — доступний для всіх виробів, незалежно від зв’язків нижче.",
            ),
        ),
        migrations.AddField(
            model_name="coefficient",
            name="products",
            field=models.ManyToManyField(
                blank=True,
                help_text="Якщо вказано — коефіцієнт доступний для цих конкретних виробів.",
                related_name="coefficients",
                to="doors.product",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="product",
            name="base_ks",
            field=models.FloatField(verbose_name="Базові к/с"),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="products/",
                verbose_name="Зображення виробу",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Назва виробу"),
        ),
        migrations.AddField(
            model_name="addition",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                help_text="Доступне для виробів цих категорій.",
                related_name="additions",
                to="doors.category",
            ),
        ),
        migrations.AddField(
            model_name="coefficient",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                help_text="Якщо вказано — коефіцієнт доступний для виробів цих категорій.",
                related_name="coefficients",
                to="doors.category",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="doors.category",
                verbose_name="Категорія",
            ),
        ),
    ]
