# Generated by Django 5.2.7 on 2025-12-01 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doors", "0013_orderimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Назва компанії"),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Адреса"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Телефон"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "website",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Сайт"
                    ),
                ),
                (
                    "iban",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="IBAN"
                    ),
                ),
                (
                    "edrpou",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="ЄДРПОУ"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="company_logo/",
                        verbose_name="Логотип",
                    ),
                ),
            ],
            options={
                "verbose_name": "Реквізити компанії",
                "verbose_name_plural": "Реквізити компанії",
            },
        ),
    ]
