# Generated by Django 5.2.7 on 2025-12-07 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doors", "0015_orderfile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("person", "Фізична особа"),
                            ("company", "Юридична особа / ФОП"),
                        ],
                        default="person",
                        max_length=20,
                        verbose_name="Тип замовника",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Наприклад: Іван Петренко або ТОВ “БудМонтаж”",
                        max_length=255,
                        verbose_name="Ім'я / Назва замовника",
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(
                        blank=True,
                        help_text="Якщо це компанія — ПІБ контактної особи",
                        max_length=255,
                        null=True,
                        verbose_name="Контактна особа",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Телефон"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "company_code",
                    models.CharField(
                        blank=True,
                        max_length=40,
                        null=True,
                        verbose_name="ЄДРПОУ / ІПН",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Адреса"
                    ),
                ),
                (
                    "telegram",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Telegram / нік",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="Нотатки по замовнику"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата створення"
                    ),
                ),
            ],
            options={
                "verbose_name": "Замовник",
                "verbose_name_plural": "Замовники",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="order",
            name="status_finance",
            field=models.CharField(
                choices=[("paid", "Сплачено"), ("awaiting_payment", "Очікує оплату")],
                default="postponed",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="doors.customer",
                verbose_name="Замовник",
            ),
        ),
    ]
