# Generated by Django 5.2.7 on 2025-12-09 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doors", "0016_customer_order_status_finance_order_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Не розпочато"),
                    ("in_progress", "В роботі"),
                    ("done", "Готово"),
                    ("canceled", "Скасовано"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Статус позиції",
            ),
        ),
    ]
