# Generated by Django 5.2.7 on 2025-12-09 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doors", "0017_orderitem_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderprogress",
            name="problem_items",
            field=models.ManyToManyField(
                blank=True,
                related_name="problem_progresses",
                to="doors.orderitem",
                verbose_name="Позиції, які неможливо виконати",
            ),
        ),
    ]
