# Generated by Django 5.2.7 on 2025-12-09 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doors", "0018_orderprogress_problem_items"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderImageMarker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("x", models.FloatField(help_text="X у %, від лівого краю")),
                ("y", models.FloatField(help_text="Y у %, від верхнього краю")),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        help_text="Необов'язковий коментар до точки",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="markers",
                        to="doors.orderimage",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image_markers",
                        to="doors.orderitem",
                    ),
                ),
            ],
        ),
    ]
