# Generated by Django 5.2.7 on 2025-12-11 19:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doors", "0019_orderimagemarker"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderimagemarker",
            name="note",
        ),
        migrations.AddField(
            model_name="orderimagemarker",
            name="color",
            field=models.CharField(default="#FF0000", max_length=7),
        ),
        migrations.AddField(
            model_name="orderimagemarker",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="orderimagemarker",
            name="item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="image_markers",
                to="doors.orderitem",
            ),
        ),
        migrations.AlterField(
            model_name="orderimagemarker",
            name="x",
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name="orderimagemarker",
            name="y",
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
