# Generated by Django 5.2.7 on 2025-12-11 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doors", "0020_remove_orderimagemarker_note_orderimagemarker_color_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("in_progress", "В роботі"),
                    ("completed", "Завершено"),
                    ("postponed", "Відкладено"),
                    ("calculation", "розрахунки"),
                ],
                default="in_progress",
                max_length=20,
            ),
        ),
    ]
