# Generated by Django 5.2.7 on 2025-12-11 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doors", "0021_alter_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("in_progress", "В роботі"),
                    ("completed", "Завершено"),
                    ("postponed", "Відкладено"),
                    ("calculation", "Розрахунки"),
                ],
                default="in_progress",
                max_length=20,
            ),
        ),
    ]
